services:
  postgres:
    image: postgres:18
    container_name: super-impress-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app

  backend:
    build:
      context: ./backend
    image: super-impress-backend
    container_name: super-impress-backend
    env_file:
      - backend/.env
    ports:
      - "8000:80"
    depends_on:
      - postgres
    networks:
      - app

  frontend:
    build:
      context: ./frontend
    image: super-impress-frontend
    container_name: super-impress-frontend
    ports:
      - "5173:5173"
    env_file:
      - frontend/.env
    depends_on:
      - backend
    networks:
      - app

volumes:
  postgres-data:

networks:
  app:
    driver: bridge
